<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>

<!-- 新增菜单弹窗 -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新增</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="status" class="col-sm-4 control-label">Status</label>
                        <div class="col-sm-8">
                          <select class="form-control js_add_status">
                            <option value="">/</option>
                            <option value ="1">show</option>
                            <option value ="0">hide</option>
                          </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="image" class="col-sm-4 control-label">Image</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_image" id="image" placeholder="image">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="urlen" class="col-sm-4 control-label">URL(en)</label>
                        <div class="col-sm-8">
                          <input type="text" class="form-control js_add_urlen" id="urlen" placeholder="URL(en)">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="urltc" class="col-sm-4 control-label">URL(tc)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_urltc" id="urltc" placeholder="URL(tc)">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 点击保存前请检查信息无误，如有需要请先备份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 编辑菜单弹窗 -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">编辑</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" class="js_update_id">
                    <div class="form-group">
                        <label for="status" class="col-sm-4 control-label">Status</label>
                        <div class="col-sm-8">
                          <select class="form-control js_update_status">
                            <option value="">/</option>
                            <option value ="1">show</option>
                            <option value ="0">hide</option>
                          </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="image" class="col-sm-4 control-label">Image</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_image" id="image" placeholder="image">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="urlen" class="col-sm-4 control-label">URL(en)</label>
                        <div class="col-sm-8">
                          <input type="text" class="form-control js_update_urlen" id="urlen" placeholder="URL(en)">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="urltc" class="col-sm-4 control-label">URL(tc)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_urltc" id="urltc" placeholder="URL(tc)">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 点击保存前请检查信息无误，如有需要请先备份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 确认删除弹窗 -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                温馨提示
            </div>
            <div class="modal-body">
                确定要删除该条数据？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary js_sure_delete">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="<?php echo $resource_url; ?>js/app/banner_index.js"></script>
