<button type="button" class="btn btn-sm btn-primary js_editbanner" data-toggle="modal" data-target="#editModal" style="margin-bottom:10px;">编辑</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>

<!-- 编辑菜单弹窗 -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">编辑</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" class="js_update_id">
                    <div class="form-group">
                        <label for="contenten" class="col-sm-4 control-label">Content(EN)</label>
                        <div class="col-sm-8">

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="contenttc" class="col-sm-4 control-label">Content(TC)</label>
                        <div class="col-sm-8">

                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 点击保存前请检查信息无误，如有需要请先备份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>


<script src="<?php echo $resource_url; ?>js/app/buy_index.js"></script>
