<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">

<div class="form-group">
    <label for="title">标题（en）</label>
    <input type="text" class="form-control" id="title_en" placeholder="请输入标题（en）" value="<?php echo $info['title_en']; ?>">
</div>
<div class="form-group">
    <label for="title">标题（tc）</label>
    <input type="text" class="form-control" id="title_tc" placeholder="请输入标题（tc）"  value="<?php echo $info['title_tc']; ?>">
</div>
<div class="form-group">
    <label for="clazz_id">分类</label>
    <select class="form-control" id="clazz_id"></select>
</div>
<div class="form-group">
    <label for="pic">封面图</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div>
        <img src="<?php echo $info['pic']; ?>" id="prevArea" style="max-width: 100px; max-height: 100px; ">
    </div>
</div>
<div class="form-group">
    <label for="descript_en">描述（en）</label>
    <textarea class="form-control" id="descript_en"><?php echo $info['descript_en']; ?></textarea>
</div>
<div class="form-group">
    <label for="descript_tc">描述（tc）</label>
    <textarea class="form-control" id="descript_tc"><?php echo $info['descript_tc']; ?></textarea>
</div>
<div class="form-group">
    <label for="content_en">正文内容（en）</label>
    <div id="content_en"></div>
</div>
<div class="form-group">
    <label for="content_tc">正文内容（tc）</label>
    <div id="content_tc"></div>
</div>
<div class="form-group">
    <label for="author">作者</label>
    <input type="text" class="form-control" id="author" placeholder="请输入作者" value="admin" value="<?php echo $info['author']; ?>">
</div>

<textarea class="js_pContent_en" style="display: none;"><?php echo $info['content_en']; ?></textarea>
<textarea class="js_pContent_tc" style="display: none;"><?php echo $info['content_tc']; ?></textarea>
<input type="hidden" class="js_update_clazz_id" value="<?php echo $info['clazz_id']; ?>">

<input type="hidden" name="nid" value="<?php echo $nid; ?>" class="js_nid">

<button type="submit" class="btn btn-primary js_submit">保存</button>

<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>js/system/content_add.js"></script>
<script type="text/javascript">
    $(function() {
        $('#content_en').summernote('code', $('.js_pContent_en').val());
        $('#content_tc').summernote('code', $('.js_pContent_tc').val());
    })
</script>
