<div class="well well-sm">
    <form class="form-inline js_searchFrom">
        <div class="form-group">
            <label for="title">标题</label>
            <input type="text" class="form-control" id="title" placeholder="输入查询的标题">
        </div>
        <button type="submit" class="btn btn-primary">搜索</button>
        |
        <button type="button" class="btn btn-success js_addContent"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新建</button>
    </form>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<script src="<?php echo $resource_url; ?>js/system/content.js"></script>
