<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">
<style media="screen">
.js_delete_pdf {
   position: relative;
   left: 10px;
   top: 0px;
   background: red;
   display: inline-block;
   width: 20px;
   height: 20px;
   text-align: center;
   color: #fff;
   font-weight: 1000;
   cursor: pointer;
}
.prev-pic {
    max-width: 400px;
    max-height: 300px;
    display: block;
    margin: 20px;
    border: 1px solid #ccc;
    padding: 10px;
}
.prev-frame {
    display: inline-block;
    position: relative;
}
.prev-frame em {
    position: absolute;
    right: 25px;
    top: 20px;
    background: red;
    display: inline-block;
    width: 20px;
    height: 20px;
    text-align: center;
    color: #fff;
    font-weight: 1000;
    cursor: pointer;
}

</style>
<div class="form-group">
    <label for="title">标题（en）</label>
    <input type="text" class="form-control" id="title_en" placeholder="请输入标题（en）" value="<?php echo $info['title_en']; ?>">
</div>
<div class="form-group">
    <label for="title">标题（tc）</label>
    <input type="text" class="form-control" id="title_tc" placeholder="请输入标题（tc）"  value="<?php echo $info['title_tc']; ?>">
</div>
<div class="form-group">
    <label for="clazz_id">分类</label>
    <select class="form-control" id="clazz_id"></select>
</div>
<div class="form-group">
    <label for="pic">圖片（媒體報導）</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div>
        <?php if($info['clazz_id']==='2'):?>
            <img src="<?php echo $info['pic']; ?>" id="prevArea" style="max-width: 100px; max-height: 100px; ">
        <?php endif;?>
    </div>
</div>
<div class="form-group">
    <label for="pic2">相冊（新聞稿及相冊）</label>
    <input id="pic2" type="file" multiple="true" value="" />
    <?php if($info['clazz_id']!=='2'):?>
    <div class="js_picPrevArea"></div>
    <?php endif;?>
</div>
<!-- <div class="form-group">
    <label for="descript_en">描述（en）</label>
    <textarea class="form-control" id="descript_en"><?php echo $info['descript_en']; ?></textarea>
</div>
<div class="form-group">
    <label for="descript_tc">描述（tc）</label>
    <textarea class="form-control" id="descript_tc"><?php echo $info['descript_tc']; ?></textarea>
</div> -->
<div class="form-group">
    <label for="content_en">正文内容（en）</label>
    <div id="content_en"></div>
</div>
<div class="form-group">
    <label for="content_tc">正文内容（tc）</label>
    <div id="content_tc"></div>
</div>
<div class="form-group">
    <label for="pdf">pdf</label>
    <a href="<?php echo $info['pdf']; ?>" target="_blank" class="js_pdf_prev" style="margin-left: 20px;"><?php echo $info['pdf']; ?></a><?php if($info['pdf']):?><em class="js_delete_pdf">x</em><?php endif;?>
    <input type="file" value="" multiple="false" id="js_upload_btn01">
    <input type="hidden" class="js_pdf" value="<?php echo $info['pdf']; ?>">
</div>
<div class="form-group">
    <label for="author">作者</label>
    <input type="text" class="form-control" id="author" placeholder="请输入作者" value="admin" value="<?php echo $info['author']; ?>">
</div>

<textarea class="js_pContent_en" style="display: none;"><?php echo $info['content_en']; ?></textarea>
<textarea class="js_pContent_tc" style="display: none;"><?php echo $info['content_tc']; ?></textarea>
<input type="hidden" class="js_update_clazz_id" value="<?php echo $info['clazz_id']; ?>">

<input type="hidden" name="nid" value="<?php echo $nid; ?>" class="js_nid">
<input type="hidden" class="js_update_pic" value='<?php echo $info['pic']; ?>'>

<button type="submit" class="btn btn-primary js_submit">保存</button>

<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>js/system/content_add.js"></script>
<script type="text/javascript">
    $(function() {
        $('#content_en').summernote('code', $('.js_pContent_en').val());
        $('#content_tc').summernote('code', $('.js_pContent_tc').val());

        $('#js_upload_btn01').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'content/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf').val(result['name']);
                    $('.js_pdf_prev').attr('href', result['name']);
                    $('.js_pdf_prev').html(result['name']);
                    $('.js_pdf_prev').after('<em class="js_delete_pdf">x</em>')
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
    })
</script>
