<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">

<style type="text/css">
    .prev-pic {
        max-width: 400px;
        max-height: 300px;
        display: block;
        margin: 20px;
        border: 1px solid #ccc;
        padding: 10px;
    }
    .prev-frame {
        display: inline-block;
        position: relative;
    }
    .prev-frame em {
        position: absolute;
        right: 25px;
        top: 20px;
        background: red;
        display: inline-block;
        width: 20px;
        height: 20px;
        text-align: center;
        color: #fff;
        font-weight: 1000;
        cursor: pointer;
    }
</style>

<div class="form-group">
    <label for="title">标题（en）</label>
    <input type="text" class="form-control" id="title_en" placeholder="请输入标题（en）">
</div>
<div class="form-group">
    <label for="title">标题（tc）</label>
    <input type="text" class="form-control" id="title_tc" placeholder="请输入标题（tc）">
</div>
<div class="form-group">
    <label for="clazz_id">分类</label>
    <select class="form-control" id="clazz_id"></select>
</div>
<div class="form-group">
    <label for="pic">图片</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div class="js_picPrevArea"></div>
</div>
<div class="form-group">
    <label for="num">标号</label>
    <input type="text" class="form-control" id="num" placeholder="请输入标号">
</div>
<div class="form-group">
    <label for="prize_en">估计价格</label>
    <input type="text" class="form-control" id="prize_en" placeholder="请输入估计价格">
</div>
<div class="form-group">
    <label for="prize_tc">成交价格</label>
    <input type="text" class="form-control" id="prize_tc" placeholder="请输入成交价格">
</div>
<div class="form-group">
    <label for="descript_en">描述（en）</label>
    <div id="descript_en"></div>
</div>
<div class="form-group">
    <label for="descript_tc">描述（tc）</label>
    <div id="descript_tc"></div>
</div>
<div class="form-group">
    <label for="pdf">pdf</label>
    <a href="" target="_blank" class="js_pdf_prev" style="margin-left: 20px;"></a>
    <input type="file" value="" multiple="false" id="js_upload_btn01">
    <input type="hidden" class="js_pdf" value="">
</div>
<div class="form-group">
    <label for="sort">排序</label>
    <input type="text" class="form-control" id="sort" placeholder="排序。数值越大，越靠前" value="100">
</div>

<input type="hidden" name="nid" value="<?php echo $nid; ?>" class="js_nid">
<input type="hidden" class="js_add_pic" value='true'>

<button type="submit" class="btn btn-primary js_submit">保存</button>

<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-TW.js"></script>
<script src="<?php echo $resource_url; ?>js/system/pic_content_add.js"></script>
<script type="text/javascript">
    $(function() {
        $('#js_upload_btn01').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'pic_content/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf').val(result['name']);
                    $('.js_pdf_prev').attr('href', result['name']);
                    $('.js_pdf_prev').html(result['name']);
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
    })
</script>
