<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <meta property="og:title" content="<?=$title?>" />
  <meta property="og:description" content="<?=$og_description?>" />
  <meta name="keywords" content="仕宏拍賣, L & H Auction">
  <meta name="description" content="<?=$description?>">
  <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/reset.css">
  <link rel="stylesheet" href="<?php echo $resource_url; ?>css/index2.css">
  <link rel="stylesheet" href="<?php echo $resource_url; ?>css/swiper.min.css">
  <script type="text/javascript" src="<?php echo $resource_url; ?>js/jquery-3.2.0.js"></script>
  <script type="text/javascript" src="<?php echo $resource_url; ?>js/common.js"></script>
</head>
<style>
<?=$css?>
</style>
<body>
  <div class="header">
    <div class="line"></div>
    <div class="wrap">
      <div class="top">
          <div class="logo">
            <a href="<?=$home?>">
              <img src="<?php echo $resource_url; ?>img/logo.png" alt="">
            </a>
          </div>
          <div class="search">
            <input type="text" name="" value="" placeholder="<?=$placeholder?>">
          </div>
          <div class="lang">
            <span><span class="en" href="">ENG</span> / <span href="" class="tc">繁</span></span>
          </div>
      </div>
      <div class="nav">
          <div class="navi home">
            <a href="<?=$home?>"><?=$navi1?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
          </div>
          <div class="navi auction">
            <a href="./auction"><?=$navi2?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
            <ul class="sub-nav">
              <li><a href="./auction"><?=$subnavi1?></a></li>
              <li style="border-bottom:1px solid #979797"><a href="./auction_past"><?=$subnavi2?></a></li>
            </ul>
          </div>
          <div class="navi catalogue">
            <a href="./catalogue"><?=$navi3?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
          </div>
          <div class="navi buy">
            <a href="./buy"><?=$navi4?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
            <ul class="sub-nav">
              <li><a href="./buy"><?=$subnavi3?></a></li>
              <li style="border-bottom:1px solid #979797"><a href="./sell"><?=$subnavi4?></a></li>
            </ul>
          </div>
          <div class="navi press_release">
            <a href="./press_release"><?=$navi5?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
            <ul class="sub-nav">
              <li><a href="./press_release"><?=$subnavi5?></a></li>
              <li style="border-bottom:1px solid #979797"><a href="./press_media"><?=$subnavi6?></a></li>
            </ul>
          </div>
          <div class="navi about" style="border-right:1px solid #979797">
            <a href="./about"><?=$navi6?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
            <ul class="sub-nav">
              <li><a href="./about"><?=$subnavi7?></a></li>
              <li style="border-bottom:1px solid #979797"><a href="./contact"><?=$subnavi8?></a></li>
            </ul>
          </div>
      </div>
    </div>
  </div>
