<div class="footer">
  <div class="wrap">
    <div class="content">
      <div class="logo">
        <img src="<?php echo $resource_url; ?>img/logo_white.png" alt="">
      </div>
      <div class="nav">
        <ul>
          <li><a href="#"><?=$contact?></a></li>
          <li><a href="#"><?=$sitemap?></a></li>
          <li><a href="#"><?=$terms?></a></li>
          <li><a href="#"><?=$privacy?></a></li>
        </ul>
        <span style="padding-top:2px;"><?=$copyright?></span>
      </div>
      <div class="icon">
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_weixin.png" alt=""></a>
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_youtube.png" alt=""></a>
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_fb.png" alt=""></a>
      </div>
    </div>
  </div>
</div>
</body>
</html>
<script type="text/javascript">
// 当前目录高亮
  var curNav = '<?=$curNav?>',
      curLang = '<?=$curLang?>';
  if(!curNav){
    $('.home').addClass('cur');
  }else{
    curNav = '.' + curNav;
    if($(curNav)){
      $(curNav).addClass('cur');
    }
  }
  $('.'+curLang).addClass('cur');
// 导航控制鼠标经过
  $('.navi').mouseover(function(){
    $(this).parent().find('.hover').removeClass('hover');
    $(this).addClass('hover');
    $(this).children('.sub-nav').addClass('hover');
  })
  $('.mid').mouseover(function(){
    $('.sub-nav').removeClass('hover');
    $('.navi').removeClass('hover');
  })
  $('.header .top').mouseover(function(){
    $('.sub-nav').removeClass('hover');
    $('.navi').removeClass('hover');
  })
// 控制切换语言url
  $('.tc').click(function(event) {
    /* Act on the event */
    var str = window.location.href;
    if(str.indexOf(/en/)>0){
      str = str.replace(/\/en\//, "/tc/");
    }
    window.location.href=str;
  });
  $('.en').click(function(event) {
    /* Act on the event */
    var str = window.location.href;
    if(str.indexOf(/en/)<0){
      str = str.replace(/\/tc\//, "/en/");
    }
    window.location.href=str;
  });
</script>
