<div class="footer">
  <div class="wrap">
    <div class="content">
      <div class="logo">
        <img src="<?php echo $resource_url; ?>img/logo_white.png" alt="">
      </div>
      <div class="nav">
        <ul>
          <li><a href="#">聯絡我們</a></li>
          <li><a href="#">網站地圖</a></li>
          <li><a href="#">條款及細則</a></li>
          <li><a href="#">個人私隱</a></li>
        </ul>
        <span>©2017 仕宏拍賣版權所有</span>
      </div>
      <div class="icon">
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_weixin.png" alt=""></a>
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_youtube.png" alt=""></a>
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_fb.png" alt=""></a>
      </div>
    </div>
  </div>
</div>
</body>
</html>
