<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <meta property="og:title" content="<?=$title?>" />
  <meta property="og:description" content="<?=$og_description?>" />
  <meta name="keywords" content="仕宏拍賣, L&H Auction">
  <meta name="description" content="<?=$description?>">
  <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/reset.css">
  <link rel="stylesheet" href="<?php echo $resource_url; ?>css/index2.css">
  <link rel="stylesheet" href="<?php echo $resource_url; ?>css/swiper.min.css">
</head>
<style>
<?=$css?>
</style>
