<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <meta property="og:title" content="<?=$title?>" />
  <meta property="og:description" content="<?=$og_description?>" />
  <meta name="keywords" content="仕宏拍賣, L&H Auction">
  <meta name="description" content="<?=$description?>">
  <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/reset.css">
  <link rel="stylesheet" href="<?php echo $resource_url; ?>css/index2.css">
  <link rel="stylesheet" href="<?php echo $resource_url; ?>css/swiper.min.css">
</head>
<style>
<?=$css?>
</style>
<body>
  <div class="header">
    <div class="line"></div>
    <div class="wrap">
      <div class="top">
          <div class="logo">
            <img src="<?php echo $resource_url; ?>img/logo.png" alt="">
          </div>
          <div class="search">
            <input type="text" name="" value="" placeholder="<?=$placeholder?>">
          </div>
          <div class="lang">
            <span><a href="#en">ENG</a>&nbsp/&nbsp<a href="#ch" class="cur">繁</a></span>
          </div>
      </div>
      <div class="nav">
          <div class="navi">
            <a href=""><?=$navi1?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
          </div>
          <div class="navi">
            <a href=""><?=$navi2?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
            <ul class="sub-nav">
              <li><?=$subnavi1?></li>
              <li style="border-bottom:1px solid #979797"><?=$subnavi2?></li>
            </ul>
          </div>
          <div class="navi">
            <a href=""><?=$navi3?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
          </div>
          <div class="navi">
            <a href=""><?=$navi4?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
          </div>
          <div class="navi cur">
            <a href=""><?=$navi5?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
          </div>
          <div class="navi" style="border-right:1px solid #979797">
            <a href=""><?=$navi6?></a>
            <div class="navbg"><img src="<?php echo $resource_url; ?>img/btn_nav_selected.png" alt=""></div>
            <ul class="sub-nav">
              <li><?=$navi6?></li>
              <li style="border-bottom:1px solid #979797"><?=$subnavi3?></li>
            </ul>
          </div>
      </div>
    </div>
    <!-- <div class="bottom">
      <div class="locate wrap">
        <span class="content">新聞中心 > 媒體報導</span>
      </div>
    </div> -->
  </div>
