<div class="footer">
  <div class="wrap">
    <div class="content">
      <div class="logo">
        <img src="<?php echo $resource_url; ?>img/logo_white.png" alt="">
      </div>
      <div class="nav">
        <ul>
          <li><a href="#"><?=$contact?></a></li>
          <li><a href="#"><?=$sitemap?></a></li>
          <li><a href="#"><?=$terms?></a></li>
          <li><a href="#"><?=$privacy?></a></li>
        </ul>
        <span style="padding-top:2px;"><?=$copyright?></span>
      </div>
      <div class="icon">
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_weixin.png" alt=""></a>
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_youtube.png" alt=""></a>
        <a href="#"><img src="<?php echo $resource_url; ?>img/btn_fb.png" alt=""></a>
      </div>
    </div>
  </div>
</div>
</body>
</html>
