  <div class="mid mid2" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi6?> > <?=$subnavi7?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu">
        <div class="nav about">
          <div class="tit cur">
            <a href="/about"><?=$subnavi7?></a>
          </div>
        </div>
        <div class="nav contact">
          <div class="tit">
            <a href="/contact"><?=$subnavi8?></a>
          </div>
        </div>
      </div>
      <div class="container3" style="border:0">
        <?php if ($curLang === 'tc'): ?>
            <?php echo $about->content_tc; ?>
          <?php else: ?>
            <?php echo $about->content_en; ?>
          <?php endif; ?>
      </div>
    </div>


  </div>
