  <div class="mid" style="height:3877px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content">拍賣會 > 今屆拍賣</span>
      </div>
    </div>
    <div class="wrap">
      <div class="menu">
        <div class="nav">
          <div class="tit">
            今屆拍賣
          </div>
        </div>
        <div class="nav cur">
          <div class="tit">
            往屆拍賣
          </div>
          <div class="sub-nav">
            <div class="sub-tit cur">
              第十屆-2017秋拍
            </div>
            <div class="sub-tit">
              第九屆-2017春拍
            </div>
          </div>
        </div>
      </div>
      <div class="container2">
        <div class="item">
          <div class="top">
            <div class="wrap2">
              <div class="tit">御養尚品 - 補品及佳釀專場【完整圖錄】</div>
              <div class="result"><a href="#">拍賣結果例表</a></div>
              <div class="date">2017-01-03</div>
            </div>
          </div>
          <div class="pics">
            <div class="wrap2">
              <img src="img/item1.jpg" alt="">
              <img src="img/item1.jpg" alt="">
              <img src="img/item1.jpg" alt="">
              <img src="img/item1.jpg" alt="">
              <img src="img/more.jpg" alt="">
            </div>
          </div>
        </div>
        <div class="item">
          <div class="top">
            <div class="wrap2">
              <div class="tit">御養尚品 - 補品及佳釀專場【完整圖錄】</div>
              <div class="result"><a href="#">拍賣結果例表</a></div>
              <div class="date">2017-01-03</div>
            </div>
          </div>
          <div class="pics">
            <div class="wrap2">
              <img src="img/item1.jpg" alt="">
              <img src="img/item1.jpg" alt="">
              <img src="img/item1.jpg" alt="">
              <img src="img/item1.jpg" alt="">
              <img src="img/more.jpg" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
<script src="<?php echo $resource_url; ?>js/auction.js" charset="utf-8"></script>
