  <div class="mid" style="">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi2?> > <?=$subnavi1?></span>
      </div>
    </div>
    <div class="wrap">
      <div class="menu">
        <div class="nav auction cur">
          <div class="tit">
            <?=$subnavi1?>
          </div>
        </div>
        <div class="nav auction_past">
          <div class="tit">
            <?=$subnavi2?>
          </div>
          <div class="sub-nav">
              <?php if ($curLang === 'tc'): ?>
                <?php foreach ($categorylist as $category): ?>
                    <div class="sub-tit"><?php echo $category['name_tc']?></div>
                <?php endforeach; ?>
              <?php else: ?>
                <?php foreach ($categorylist as $category): ?>
                    <div class="sub-tit"><?php echo $category['name_en']?></div>
                <?php endforeach; ?>
              <?php endif; ?>
          </div>
        </div>
      </div>
      <div class="container2" style="border:0">
          <?php echo $newcontent->content_tc; ?>
      </div>
    </div>

  </div>
<script src="<?php echo $resource_url; ?>js/auction.js" charset="utf-8"></script>
