  <div class="mid" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi3?></span>
      </div>
    </div>
    <div class="wrap">
      <div class="menu2">

        <?php if ($curLang === 'tc'): ?>
          <?php foreach ($categorylist as $category): ?>
            <div class="nav" data-aid="<?php echo $category['id']?>">
              <div class="tit">
                <?php echo $category['name_tc']?>
              </div>
              <?php if(isset($category['sub_nav'])): ?>
              <?php foreach ($category['sub_nav'] as $subnav): ?>
              <div class="sub-navi">
                <a href="catalogue?cid=<?php echo $subnav['id']?>" class="sub-tit" data-cid="<?php echo $subnav['id']?>">
                  <?php echo $subnav['name_tc']?>
                </a>
                <a href="" class="download"></a>
              </div>
              <?php endforeach; ?>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        <?php else: ?>
          <?php foreach ($categorylist as $category): ?>
            <div class="nav">
              <div class="tit">
                <?php echo $category['name_en']?>
              </div>
              <div class="sub-navi">
                <a href="" class="sub-tit"></a>
                <span></span>
                <a href="" class="download"></a>
              </div>
            </div>
          <?php endforeach; ?>
        <?php endif; ?>
<!--
        <div class="nav">
          <div class="tit">
            第十屆-2017秋拍
          </div>
        </div>
        <div class="nav cur">
          <div class="tit">
            第九屆-2017春拍
          </div>
          <div class="sub-nav">
            <div class="sub-navi cur">
              <a class="sub-tit" href=""><span>御養尚品 - 補品及佳釀專場</span></a>
              <a class="download" href=""></a>
            </div>
            <div class="sub-navi">
              <a class="sub-tit" href="#"><span>御養尚品 - 補品及佳釀專場</span></a>
              <a class="download" href=""></a>
            </div>
          </div>
        </div>
        <div class="nav">
          <div class="tit">
            第十屆-2017秋拍
          </div>
        </div> -->
      </div>
      <div class="container container2">
        <div class="news">
          <span>仕宏2017年秋季拍賣會將於5月28日假香港君悅酒店舉行，歡迎蒞臨參觀，</span><a href=""><span>參與競投。</span></a>
        </div>
        <div class="performance">
          <div class="top">
            <div class="wrap2">
              <div class="tit">
                <?php echo $catalogueParent->name_tc; ?>
              </div>
            </div>
          </div>
          <?php foreach ($catalogue as $k => $v): ?>
            <div class="item">
              <div class="info">
                <div class="wrap2">
                  <div class="pic">
                    <?php if(strpos($v['pic'],',')): ?>
                      <img src="<?php echo strstr($v['pic'], ',', TRUE) ?>" alt="">
                    <?php else: ?>
                      <img src="<?php echo $v['pic'] ?>" alt="">
                    <?php endif; ?>
                  </div>
                  <div class="detail">
                    <div class="name"><?php echo $v['title_tc']; ?></div>
                    <div class="lot">LOT: <span class="no"><?php echo $v['num']; ?></span></div>
                    <div class="estimated">
                      估計價格：HK$ <span class="money"><?php echo $v['prize_en']; ?></span>
                    </div>
                    <div class="instruction">
                      <?php echo $v['descript_tc']; ?>
                    </div>
                  </div>
                  <div class="more">
                    <a href="">Read More</a>
                  </div>
                </div>
              </div>
            </div>
          <?php endforeach; ?>

        </div>
      </div>
    </div>


  </div>
<script src="<?php echo $resource_url; ?>js/catalogue.js" charset="utf-8"></script>
