<div class="mid">
  <div class="bottom">
    <div class="locate wrap">
      <span class="content"><?=$navi3?> > <?=$subnavi9?></span>
    </div>
  </div>
  <div class="wrap">
    <div class="performance">
        <div class="top">
          <div class="wrap2">
              <div class="tit">

              </div>
              <div class="pdf">
                  <a href="" class="download"></a>
              </div>
          </div>
        </div>
          <div class="item">
            <div class="info">
              <div class="wrap2">
                <div class="pic">
                    <a href="">
                      <!-- <img src="<?php echo strstr($v['pic'], ',', TRUE) ?>" alt=""> -->
                    </a>
                </div>
                <div class="detail">
                  <div class="name"><a href=""></a></div>
                  <div class="lot">LOT: <span class="no"></span></div>
                  <div class="estimated">
                    估計價格：HK$ <span class="money"></span>
                  </div>
                  <div class="instruction">
                    <!-- <?php echo $v['descript_tc']; ?> -->
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>

  </div>
</div>
<script src="<?php echo $resource_url; ?>js/swiper.min.js"></script>
<script src="<?php echo $resource_url; ?>js/catalogue_detail.js" charset="utf-8"></script>
