  <div class="mid mid2" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi6?> > <?=$subnavi8?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu">
        <div class="nav about">
          <div class="tit">
            <a href="<?=$home?>about"><?=$subnavi7?></a>
          </div>
        </div>
        <div class="nav contact">
          <div class="tit cur">
            <a href="<?=$home?>contact"><?=$subnavi8?></a>
          </div>
        </div>
      </div>
      <div class="container3" style="border:0">
        <div id="map" style="width:665px; height:390px; border:1px solid #5C6672;"></div>
        <?php if ($curLang === 'tc'): ?>
            <?php echo $contact1->content_tc; ?>
          <?php else: ?>
            <?php echo $contact1->content_en; ?>
          <?php endif; ?>
      </div>
    </div>


  </div>
  <script>
    function initMap() {
      var uluru = {lat: 22.294715099827147, lng: 114.16928887367249};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 17,
        center: uluru
      });
      var marker = new google.maps.Marker({
        position: uluru,
        map: map
      });
    }
  </script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCalpFBYzyuaPac83svQNjQg-NqpoaOJfs&callback=initMap">
  </script>
