  <div class="mid mid2" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi6?> > <?=$subnavi8?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu">
        <div class="nav about">
          <div class="tit">
            <?=$subnavi7?>
          </div>
        </div>
        <div class="nav contact">
          <div class="tit">
            <?=$subnavi8?>
          </div>
        </div>
      </div>
      <div class="container3">
      </div>
    </div>


  </div>
<script src="<?php echo $resource_url; ?>js/auction.js" charset="utf-8"></script>
