  <div class="mid" style="height:3877px;margin-top:70px">
    <div class="banner">
      <!-- Swiper -->
      <div class="swiper-container gallery-top">
          <div class="swiper-wrapper">
            <?php foreach ($bannerlist as $banner): ?>
              <div class="swiper-slide" style="background-image:url(<?php echo $banner['pic']?>)"></div>
            <?php endforeach; ?>
          </div>
          <!-- Add Arrows -->
          <div class="swiper-button-next swiper-button-white"></div>
          <div class="swiper-button-prev swiper-button-white"></div>
      </div>
      <div class="swiper-container gallery-thumbs">
          <div class="swiper-wrapper">
            <?php foreach ($bannerlist as $banner): ?>
              <div class="swiper-slide" style="background-image:url(<?php echo $banner['pic']?>)"></div>
            <?php endforeach; ?>
          </div>
      </div>
    </div>
    <div class="news">
      <div class="wrap">
        <?php if ($curLang === 'tc'): ?>
        <div class="head">
          <div class="tit"><a href="<?=$home?>auction">最新動態</a></div>
          <div class="more"><a href="<?=$home?>auction">Read More</a></div>
        </div>
        <div class="content">
          <div class="pic">
            <a href="#">
              <a href=""><img src=<?php echo $newcontent->pic; ?> alt=""></a>
            </a>
          </div>
          <div class="article">
            <span class="tit"><?php echo $newcontent->title_tc; ?></span>
            <p class="time"><?php echo date("M/d/Y", $newcontent->create_time); ?></p>
            <p class="cont"><?php echo $newcontent->descript_tc?></p>
            <span class="detail"><a href="<?=$home?>auction">詳情</a></span>
          </div>
        </div>
        <?php else: ?>
          <div class="head">
            <div class="tit"><a href="<?=$home?>auction">NEWS</a></div>
            <div class="more"><a href="<?=$home?>auction">Read More</a></div>
          </div>
          <div class="content">
            <div class="pic">
              <a href="#">
                <a href=""><img src=<?php echo $newcontent->pic; ?> alt=""></a>
              </a>
            </div>
            <div class="article">
              <span class="tit"><?php echo $newcontent->title_en; ?></span>
              <p class="time"><?php echo date("M/d/Y", $newcontent->create_time); ?></p>
              <p class="cont"><?php echo $newcontent->descript_en?></p>
              <span class="detail"><a href="<?=$home?>auction">DETAILS</a></span>
            </div>
          </div>
        <?php endif; ?>

      </div>
    </div>
    <div class="products">
    <?php if ($curLang === 'tc'): ?>
      <?php foreach ($pic_clazz as $items): ?>
      <div class="product1">
        <div class="wrap">
          <div class="head">
            <div class="tit"><a href="<?=$home?>catalogue?cid=<?php echo $items['id']?>"><?php echo $items['name_tc'] ?></a></div>
            <div class="more"><a href="<?=$home?>catalogue?cid=<?php echo $items['id']?>">Read More</a></div>
          </div>
          <?php foreach ($items['pic_content'] as $item): ?>
          <div class="item cur">
            <div class="img">
              <?php if(strpos($item['pic'],',')): ?>
                <a href="<?=$home?>catalogue/detail?id=<?php echo $item['id']?>">
                  <img src="<?php echo strstr($item['pic'], ',', TRUE) ?>" alt="">
                </a>
              <?php else: ?>
                <a href="<?=$home?>catalogue/detail?id=<?php echo $item['id']?>">
                  <img src="<?php echo $item['pic'] ?>" alt="">
                </a>
              <?php endif; ?>
            </div>
            <div class="detail">
              <div class="name">
                <?php echo $item['title_tc']; ?>
              </div>
              <div class="lot">
                LOT : <span class="no"><?php echo $item['num']; ?></span>
              </div>
              <div class="estimated">
                估計價格：HK$ <span class="money"><?php echo $item['prize_en']; ?></span>
              </div>
              <div class="instruction">
                <?php echo $item['descript_tc']; ?>
              </div>
            </div>
          </div>
          <?php endforeach; ?>
        </div>
      </div>
      <?php endforeach; ?>
    <?php else: ?>
      <?php foreach ($pic_clazz as $items): ?>
      <div class="product1">
        <div class="wrap">
          <div class="head">
            <div class="tit"><a href="<?=$home?>catalogue?cid=<?php echo $items['id']?>"><?php echo $items['name_en'] ?></a></div>
            <div class="more"><a href="<?=$home?>catalogue?cid=<?php echo $items['id']?>">Read More</a></div>
          </div>
          <?php foreach ($items['pic_content'] as $item): ?>
          <div class="item cur">
            <div class="img">
              <?php if(strpos($item['pic'],',')): ?>
                <a href="<?=$home?>catalogue/detail?id=<?php echo $item['id']?>">
                  <img src="<?php echo strstr($item['pic'], ',', TRUE) ?>" alt="">
                </a>
              <?php else: ?>
                <a href="<?=$home?>catalogue/detail?id=<?php echo $item['id']?>">
                  <img src="<?php echo $item['pic'] ?>" alt="">
                </a>
              <?php endif; ?>
            </div>
            <div class="detail">
              <div class="name">
                <?php echo $item['title_en']; ?>
              </div>
              <div class="lot">
                LOT : <span class="no"><?php echo $item['num']; ?></span>
              </div>
              <div class="estimated">
                ESTIMATE PRICE：HK$ <span class="money"><?php echo $item['prize_en']; ?></span>
              </div>
              <div class="instruction">
                <?php echo $item['descript_en']; ?>
              </div>
            </div>
          </div>
          <?php endforeach; ?>
        </div>
      </div>
      <?php endforeach; ?>
    <?php endif; ?>
    </div>

    <!-- <div class="tit"><a href="">鑾器天香<div class="all-tit">·茶道.香道.花器專場【完整圖錄】</div></a></div> -->
<script src="<?php echo $resource_url; ?>js/swiper.min.js"></script>
<script src="<?php echo $resource_url; ?>js/index.js" charset="utf-8"></script>
