  <div class="mid mid2" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi5?> > <?=$subnavi5?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu">
        <div class="nav press_release">
          <div class="tit">
            <?=$subnavi5?>
          </div>
        </div>
        <div class="nav press_media">
          <div class="tit">
            <?=$subnavi6?>
          </div>
        </div>
      </div>
      <div class="container3">
        <div class="item">
          <div class="pic">
            <img src="img/new1.png" alt="">
          </div>
          <div class="detail">
            <div class="tit">
              歷史級陳年普洱系列收藏 「普洱印級茶一條龍」將於香港國際茶展率先展出
            </div>
            <div class="article">
              以香港為基地的仕宏拍賣有限公司成立於2013年，秉承「仕以高品而宏」之專業態度及宗旨，力求為收藏興趣愈益多元化的藏家們提供炙手可熱的藏品，將旗下拍賣活動打造成為收藏家們搜尋頂級珍品的良機盛會。
            </div>
            <div class="date">
              2017-10-10
            </div>
          </div>
        </div>
        <div class="item">
          <div class="pic">
            <img src="img/new1.png" alt="">
          </div>
          <div class="detail">
            <div class="tit">
              歷史級陳年普洱系列收藏 「普洱印級茶一條龍」將於香港國際茶展率先展出
            </div>
            <div class="article">
              以香港為基地的仕宏拍賣有限公司成立於2013年，秉承「仕以高品而宏」之專業態度及宗旨，力求為收藏興趣愈益多元化的藏家們提供炙手可熱的藏品，將旗下拍賣活動打造成為收藏家們搜尋頂級珍品的良機盛會。
            </div>
            <div class="date">
              2017-10-10
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
<script src="<?php echo $resource_url; ?>js/auction.js" charset="utf-8"></script>
