<div class="mid">
  <div class="bottom">
    <div class="locate wrap">
      <span class="content"><?=$navi5?> > <?=$subnavi5?></span>
    </div>
  </div>
  <div class="wrap">
    <div class="menu <?=$curLang?>">
      <div class="nav press_release">
        <div class="tit">
          <?=$subnavi5?>
        </div>
        <div class="sub-nav">
            <?php if ($curLang === 'tc'): ?>
              <?php foreach ($submenu as $sub): ?>
                  <div class="sub-tit" data-id="<?=$sub['id']?>"><a href="<?=$home?>press_release?id=<?=$sub['id']?>"><?php echo $sub['name_tc']?></a></div>
              <?php endforeach; ?>
            <?php else: ?>
              <?php foreach ($submenu as $sub): ?>
                  <div class="sub-tit" data-id="<?=$sub['id']?>"><a href="<?=$home?>press_release?id=<?=$sub['id']?>"><?php echo $sub['name_en']?></a></div>
              <?php endforeach; ?>
            <?php endif; ?>
        </div>
      </div>
      <div class="nav press_media">
        <div class="tit">
          <a href="<?=$home?>press_media">
            <?=$subnavi6?>
          </a>
        </div>
      </div>
    </div>
    <style media="screen">
      .pressitem .top{width: 100%; height: 30px;margin-bottom: 30px}
      .pressitem .top .date,.pressitem .top .pdf,.pressitem .top .return{line-height: 30px}
      .pressitem .top .date,.pressitem .top .pdf{float: left}
      .pressitem .top .date span{padding-right: 25px;border-right: 1px solid black}
      .pressitem .top .pdf span{padding-left: 25px}
      .pressitem .top .pdf span a{display: inline;color: #b8262b;}
      .pressitem .top .return{float: right}
      .pressitem .title{font-size: 18px;color: #191919;font-weight: bold;margin-bottom: 30px}
    </style>
    <div class="container3 <?=$curLang?>">
      <?php if ($curLang === 'tc'): ?>
        <div class="pressitem">
          <div class="top">
            <div class="date"><span><?=date('Y-m-d', $pressDetail->create_time)?></span></div>
            <div class="pdf"><span><a href="<?=$pressDetail->pdf?>">PDF版本</a></span></div>
            <div class="return"><a href="<?=$_SERVER['HTTP_REFERER']?>">< 返回</a></div>
          </div>
          <div class="title">
            <?=$pressDetail->title_tc?>
          </div>
          <!-- <div class="pics">
            <?php foreach ($pressDetail->pic as $v): ?>
              <img src="<?php echo $v?>" alt="">
            <?php endforeach; ?>
          </div> -->
          <div class="detail">
            <?=$pressDetail->content_tc?>
          </div>
        </div>
      <?php else:?>
        <div class="pressitem">
          <div class="top">
            <div class="date"><span><?=date('Y-m-d', $pressDetail->create_time)?></span></div>
            <div class="pdf"><span><a href="<?=$pressDetail->pdf?>">PDF版本</a></span></div>
            <div class="return"><a href="<?=$_SERVER['HTTP_REFERER']?>">< 返回</a></div>
          </div>
          <div class="title">
            <?=$pressDetail->title_en?>
          </div>
          <!-- <div class="pics">
            <?php foreach ($pressDetail->pic as $v): ?>
              <img src="<?php echo $v?>" alt="">
            <?php endforeach; ?>
          </div> -->
          <div class="detail">
            <?=$pressDetail->content_en?>
          </div>
        </div>
      <?php endif;?>
    </div>
  </div>
</div>
<!-- <script src="<?php echo $resource_url; ?>js/catalogue_detail.js" charset="utf-8"></script> -->
