  <div class="mid" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi5?> > <?=$subnavi6?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu">
        <div class="nav">
          <div class="tit">
            <?=$subnavi5?>
          </div>
          <div class="sub-nav">
              <?php if ($curLang === 'tc'): ?>
                <?php foreach ($submenu as $sub): ?>
                    <div class="sub-tit" data-id="<?=$sub['id']?>"><a href="./press_release?id=<?=$sub['id']?>"><?php echo $sub['name_tc']?></a></div>
                <?php endforeach; ?>
              <?php else: ?>
                <?php foreach ($submenu as $sub): ?>
                    <div class="sub-tit"><a href="./press_release?id=<?=$sub['id']?>"><?php echo $sub['name_en']?></a></div>
                <?php endforeach; ?>
              <?php endif; ?>
          </div>
        </div>
        <div class="nav cur">
          <div class="tit">
            <?=$subnavi6?>
          </div>
        </div>
      </div>
      <div class="container3">
        <?php if ($curLang === 'tc'): ?>
        <?php foreach ($searchNews as $new): ?>
          <div class="item">
            <div class="pic">
              <?php if(strpos($new['pic'],',')): ?>
                <img src="<?php echo strstr($new['pic'], ',', TRUE) ?>" alt="">
              <?php else: ?>
                <img src="<?php echo $new['pic'] ?>" alt="">
              <?php endif; ?>
            </div>
            <div class="detail">
              <div class="tit">
                <?php echo $new['title_tc'] ?>
              </div>
              <div class="article">
                <?php echo $new['descript_tc'] ?>
              </div>
              <div class="date">
                <?php echo date('y-m-d',$new['create_time']) ?>
              </div>
              <div class="author">
                <?php echo $new['author'] ?>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
        <?php else: ?>
          <?php foreach ($searchNews as $new): ?>
            <div class="item">
              <div class="pic">
                <?php if(strpos($new['pic'],',')): ?>
                  <img src="<?php echo strstr($new['pic'], ',', TRUE) ?>" alt="">
                <?php else: ?>
                  <img src="<?php echo $new['pic'] ?>" alt="">
                <?php endif; ?>
              </div>
              <div class="detail">
                <div class="tit">
                  <?php echo $new['title_en'] ?>
                </div>
                <div class="article">
                  <?php echo $new['descript_en'] ?>
                </div>
                <div class="date">
                  <?php echo date('y-m-d',$new['create_time']) ?>
                </div>
                <div class="author">
                  <?php echo $new['author'] ?>
                </div>
              </div>
            </div>
          <?php endforeach; ?>

        <?php endif; ?>
      </div>
    </div>


  </div>
<script src="<?php echo $resource_url; ?>js/auction.js" charset="utf-8"></script>
