  <div class="mid mid2" style="height:1472px">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi4?> > <?=$subnavi4?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu">
        <div class="nav buy">
          <div class="tit">
            <?=$subnavi3?>
          </div>
        </div>
        <div class="nav sell">
          <div class="tit">
            <?=$subnavi4?>
          </div>
        </div>
      </div>
      <div class="container3">
      </div>
    </div>


  </div>
<script src="<?php echo $resource_url; ?>js/auction.js" charset="utf-8"></script>
