<div class="mid4 terms">
  <div class="bottom">
    <div class="locate wrap">
      <span class="content"><?=$sitemap?></span>
    </div>
  </div>
  <div class="wrap">
      <div class="container" style="border:0">
        <div class="tit">
          <?=$tandc->title_tc?>
        </div>
        <div class="contant">
          <?=$tandc->content_tc?>
        </div>
      </div>
  </div>
</div>
<!-- <script src="<?php echo $resource_url; ?>js/swiper.min.js"></script> -->
<!-- <script src="<?php echo $resource_url; ?>js/catalogue_detail.js" charset="utf-8"></script> -->
